name: Docker CI/CD

on: 
    pull_request:
        paths:
            - "app/**"
            - ".github/workflows/docker.yml"

    push:
        branches:
            - main
        paths:
            - "app/**"
            - ".github/workflows/docker.yml"

permissions:
    content: read
    id-token: write

env:
    GCP_REGION: us-east1
    ARTIFACT_REPOSITORY: cloud-run-images
    IMAGE_NAME: cloud-run-app
    CLOUD_RUN_SERVICE: gcp-ai-dev